// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzgeW6h42oG7AfK7sirsYy5mZMOJ3f7GI',
    appId: '1:106034905904:web:1b808b46c47ddf7e62bef5',
    messagingSenderId: '106034905904',
    projectId: 'playlist-pursuit-efbb3',
    authDomain: 'playlist-pursuit-efbb3.firebaseapp.com',
    storageBucket: 'playlist-pursuit-efbb3.appspot.com',
    measurementId: 'G-G9ELJVQ8RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtdbBm_m3yPvSbmKkt0qXsH0zpiWxmilk',
    appId: '1:106034905904:android:7cab0db8c90d062162bef5',
    messagingSenderId: '106034905904',
    projectId: 'playlist-pursuit-efbb3',
    storageBucket: 'playlist-pursuit-efbb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7oDVuozt1-ZaUR6QShHBWT775IqyGkwM',
    appId: '1:106034905904:ios:fc6309e0d09c2b3162bef5',
    messagingSenderId: '106034905904',
    projectId: 'playlist-pursuit-efbb3',
    storageBucket: 'playlist-pursuit-efbb3.appspot.com',
    iosBundleId: 'com.example.SeniorProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7oDVuozt1-ZaUR6QShHBWT775IqyGkwM',
    appId: '1:106034905904:ios:b8aebec4805feca062bef5',
    messagingSenderId: '106034905904',
    projectId: 'playlist-pursuit-efbb3',
    storageBucket: 'playlist-pursuit-efbb3.appspot.com',
    iosBundleId: 'com.example.queueQuandry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzgeW6h42oG7AfK7sirsYy5mZMOJ3f7GI',
    appId: '1:106034905904:web:a5966b291dd19c7a62bef5',
    messagingSenderId: '106034905904',
    projectId: 'playlist-pursuit-efbb3',
    authDomain: 'playlist-pursuit-efbb3.firebaseapp.com',
    storageBucket: 'playlist-pursuit-efbb3.appspot.com',
    measurementId: 'G-ZPFWBYBJFC',
  );
}
